### ISSUE TITLE
Getting Error "Urgent please help"

### ISSUE THREAD

**Issue by shashidhar1234** [davehunt/flynnid#2]
Getting Error while i run to install a node from flynnid folder in c driver

Python 3.4.1
windows server

C:\Python34\Lib\site-packages\flynnid>flynnid --nodeport=8080 --browsername=andr
oid --browserver=2.3.3 --platform=ANDROID
  File "C:\Python34\Lib\site-packages\flynnid\flynnid.py", line 131
    print 'Using JSON request: %s' % data
                                 ^
SyntaxError: invalid syntax

and 

If i run from scripts getting the below error

C:\Python34\Scripts>flynnid --nodeport=8080 --browsername=android --browserver=2
.3.3 --platform=ANDROID
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2032, in load
    entry = getattr(entry,attr)
AttributeError: 'module' object has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\flynnid-script.py", line 9, in <module>
    load_entry_point('FlynnID==0.3', 'console_scripts', 'flynnid')()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 353, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2302, in load_entr
y_point
    return ep.load()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2034, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'flynnid' from 'C:\Python34\lib\site-packages\flynnid-0
.3-py3.4.egg\flynnid\__init__.py'> has no 'main' attribute

**Comment by davehunt** [comment]
This could be a Python 3.4 compatibility issue. I've only ever run FlynnID with Python 2.7. If you figure it out please provide a patch, otherwise feel free to fork the repository and apply any fixes there.
